version: '2.4'
services:  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: lab-pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres    
    ports:
      - "5433:80"
    depends_on:
      - postgres    
    networks:
      otel:

  minio:
    image:  quay.io/minio/minio
    entrypoint: sh
    command:   '-c ''mkdir -p /minio_data/raw && mkdir -p /minio_data/trusted && minio server /minio_data --console-address ":9001"'''
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: cursolab
      MINIO_SECRET_KEY: cursolab
    volumes:
      - ./minio/data1:/minio_data
    networks:
      otel:

  postgres: 
    image: fia_postgres_alpine18
    container_name: postgres
    hostname: postgres
    
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    ports:   
      - "5435:5432"
    volumes:
      - ./postgresql/volume:/var/lib/postgresql/data
      - ./util:/util
    environment:   
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200 -c wal_level=logical
    networks:
      otel:

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    hostname: nifi
    volumes:
      - ./nifi/util:/util
      - ./nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ./nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./nifi/state:/opt/nifi/nifi-current/state
      - ./nifi/conf:/opt/nifi/nifi-current/conf
      - ./util:/util
    environment:
      NIFI_WEB_HTTP_PORT: "9090"
      NIFI_WEB_HTTPS_HOST: "nifi"
      TZ: "America/Sao_Paulo"
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/$$TZ /etc/localtime && echo $$TZ > /etc/timezone"
    
    ports:
      - 49090:9090
    deploy:
      resources:
        limits:
          memory: 2g
          #cpus: '0.2'
    networks:
      otel: